esphome:
  name: mmwave
  friendly_name: mmwave

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Randomly-generated 32-byte base64 encoded string
# https://esphome.io/components/api.html#configuration-variables
api:
  encryption:
    key: "generate-base-64-encoded-random-string"

ota:
  - platform: esphome
    password: "18e724ebc929745dbfd7ead397089369"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# https://esphome.io/components/sensor/ld2410.html
ld2410:

uart:
  tx_pin: GPIO26
  rx_pin: GPIO14
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
